title: "CSE 211, Fall 2023"
description: "Graduate Compiler Design"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "default", "dark", "dirt", "neon", "mint", "plum", "sunrise"

paginate: 5 # number of posts to show
paginate_path: /page:num/

repository: "SorensenUCSC/CSE211-fa2023"

baseurl: "/CSE211-fa2023"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
